/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\软件\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-190d72b2",
    path: "/theme-reco/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-190d72b2").then(next)
    },
  },
  {
    path: "/theme-reco/index.html",
    redirect: "/theme-reco/"
  },
  {
    name: "v-3c179034",
    path: "/theme-reco/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c179034").then(next)
    },
  },
  {
    name: "v-d6846c78",
    path: "/theme-reco/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6846c78").then(next)
    },
  },
  {
    name: "v-a9837ed4",
    path: "/theme-reco/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9837ed4").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]